server:
  port: 8080
  servlet:
    context-path: /client-onboarding

spring:
  application:
    name: client-onboarding-service
  
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:onboardingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Integration Configuration
  integration:
    poller:
      fixed-delay: 1000
      max-messages-per-poll: 10
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-apigee-instance.apigee.net/oauth2/tokeninfo
          jwk-set-uri: https://your-apigee-instance.apigee.net/oauth2/tokeninfo

# Logging Configuration
logging:
  level:
    com.adyanta.onboarding: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: logs/client-onboarding.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# MongoDB Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/client_onboarding}
      database: ${MONGODB_DATABASE:client_onboarding}
      username: ${MONGODB_USERNAME:onboarding_user}
      password: ${MONGODB_PASSWORD:onboarding_pass}
      ssl:
        enabled: ${MONGODB_SSL_ENABLED:false}
        invalid-hostname-allowed: ${MONGODB_SSL_INVALID_HOSTNAME_ALLOWED:false}
        keystore:
          path: ${MONGODB_KEYSTORE_PATH:/app/keystore/keystore.jks}
          password: ${MONGODB_KEYSTORE_PASSWORD:}
        truststore:
          path: ${MONGODB_TRUSTSTORE_PATH:/app/keystore/truststore.jks}
          password: ${MONGODB_TRUSTSTORE_PASSWORD:}
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:2000ms}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:0}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1ms}
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:1800000} # 30 minutes
      cache-null-values: false
      enable-statistics: true

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: false
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    docExpansion: none
    showExtensions: true
    showCommonExtensions: true
    deepLinking: true
    showRequestHeaders: true
    supportedSubmitMethods:
      - get
      - post
      - put
      - delete
      - patch
  show-actuator: true
  group-configs:
    - group: 'client-onboarding'
      display-name: 'Client Onboarding API'
      paths-to-match: '/api/v1/onboarding/**'
    - group: 'fenergo-integration'
      display-name: 'Fenergo Integration API'
      paths-to-match: '/api/v1/fenergo/**'
    - group: 'mongodb-testing'
      display-name: 'MongoDB Testing API'
      paths-to-match: '/api/v1/mongo/**'
    - group: 'jwt-token-management'
      display-name: 'JWT Token Management API'
      paths-to-match: '/api/v1/jwt/**'
    - group: 'monitoring'
      display-name: 'Monitoring & Health API'
      paths-to-match: '/actuator/**'

# JWT Token Configuration
jwt:
  token:
    service:
      url: ${JWT_TOKEN_SERVICE_URL:http://localhost:8080/oauth/token}
    client:
      id: ${JWT_CLIENT_ID:your-client-id}
      secret: ${JWT_CLIENT_SECRET:your-client-secret}
    scope: ${JWT_TOKEN_SCOPE:api.read api.write}
    grant:
      type: ${JWT_GRANT_TYPE:client_credentials}
    cache:
      renewal:
        buffer: ${JWT_RENEWAL_BUFFER:20} # seconds before expiry to renew

# Service URLs
kyc:
  service:
    url: http://localhost:8081/kyc/verify
    timeout: 30000

data:
  processor:
    service:
      url: http://localhost:8082/data/process
      timeout: 30000

reference:
  data:
    service:
      url: http://localhost:8083/reference/data
      timeout: 30000

les:
  service:
    url: http://localhost:8084/les/verify
    timeout: 30000

notification:
  service:
    url: http://localhost:8085/notification/send
    timeout: 30000

# Apigee Configuration
apigee:
  base:
    url: https://your-apigee-instance.apigee.net
  client:
    id: your-client-id
    secret: your-client-secret
  timeout: 30000

# Fenergo Configuration
fenergo:
  api:
    base:
      url: https://your-fenergo-instance.fenergo.com/api/v1
    timeout: 30000
    client:
      id: your-fenergo-client-id
      secret: your-fenergo-client-secret
    tenant:
      id: your-fenergo-tenant-id
  integration:
    enabled: true
    auto-create-entities: true
    auto-create-journeys: true
    default-policy: "STANDARD_ONBOARDING"
    default-journey-type: "ONBOARDING"

# Circuit Breaker Configuration
resilience4j:
  timelimiter:
    instances:
      kyc-service:
        timeout-duration: 30s
      data-processor-service:
        timeout-duration: 30s
      reference-data-service:
        timeout-duration: 30s
      les-service:
        timeout-duration: 30s
      notification-service:
        timeout-duration: 30s
  retry:
    instances:
      kyc-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      data-processor-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      reference-data-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      les-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      notification-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      kyc-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      data-processor-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      reference-data-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      les-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      notification-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5



