{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.keystore.name }}
  labels:
    {{- include "client-onboarding.labels" . | nindent 4 }}
    component: mongodb
    type: keystore
type: Opaque
data:
  # Keystore files (base64 encoded)
  keystore.jks: {{ .Values.mongodb.keystore.jks | b64enc | quote }}
  keystore.p12: {{ .Values.mongodb.keystore.p12 | b64enc | quote }}
  truststore.jks: {{ .Values.mongodb.keystore.truststore | b64enc | quote }}
  keystore-password: {{ .Values.mongodb.keystore.password | b64enc | quote }}
  truststore-password: {{ .Values.mongodb.keystore.truststorePassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.ssl.name }}
  labels:
    {{- include "client-onboarding.labels" . | nindent 4 }}
    component: mongodb
    type: ssl
type: Opaque
data:
  # SSL certificates (base64 encoded)
  mongodb-cert.pem: {{ .Values.mongodb.ssl.cert | b64enc | quote }}
  mongodb-key.pem: {{ .Values.mongodb.ssl.key | b64enc | quote }}
  ca-cert.pem: {{ .Values.mongodb.ssl.ca | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.connection.name }}
  labels:
    {{- include "client-onboarding.labels" . | nindent 4 }}
    component: mongodb
    type: connection
type: Opaque
stringData:
  # MongoDB connection details
  mongodb-uri: {{ .Values.mongodb.connection.uri | quote }}
  mongodb-database: {{ .Values.mongodb.auth.database | quote }}
  mongodb-username: {{ .Values.mongodb.auth.username | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | quote }}
  mongodb-auth-database: {{ .Values.mongodb.auth.authDatabase | default "admin" | quote }}
  mongodb-ssl-enabled: {{ .Values.mongodb.ssl.enabled | quote }}
  mongodb-ssl-invalid-hostname-allowed: {{ .Values.mongodb.ssl.allowInvalidHostnames | quote }}
{{- end }}
